### ISSUE TITLE
Explain check section more, what attrs exist

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http-quickstart-scala.g8#13]
Explain check section more, what attrs exist

Follow up to https://github.com/akka/akka-http-scala-seed.g8/pull/12#discussion_r132506029

**Comment by jiminhsieh** [comment]
@jlprat I saw your comment - https://github.com/akka/akka-http-quickstart-scala.g8/pull/12#discussion_r132506029. Do you mean the table of inspectors on the [`Route TestKit`](https://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/testkit.html)? If I am correct, I could send a PR that links to this page. However, the table of inspectors doesn't have header anchor, I could not link to the table of inspectors directly.

**Comment by ktoso** [comment]
Yeah I mean exactly that table, PR would be welcome!
At the same time we could add a `### heading` perhaps in akka-http so in next release we'd link to that perhaps some day?

**Comment by jlprat** [comment]
Yes, that's what I meant 🙂

**Comment by jiminhsieh** [comment]
> At the same time we could add a ### heading perhaps in akka-http so in next release we'd link to that perhaps some day?

I agreed. This thought that had occurred to me too.

There are two ways I could do: 
* After Akka-HTTP adds the header anchor, I send the PR.

or 
* I send the PR without fragment identifier now. I send the second PR after Akka-HTTP has the anchor.

I would try to open an issue at Akka-HTTP for this one or maybe this could be a PR directly since this is relative trivial.

**Comment by ktoso** [comment]
Since we want to release akka http this week soon, you can submit the header PR right now into akka-http, and we'll soon release and you can already send the PR here, which will be merged once akka http is released :)

**Comment by ktoso** [comment]
FYI @jrudolph

**Comment by jlprat** [comment]
Another Akka HTTP release?

**Comment by ktoso** [comment]
Whoops, I missed that 10.0.11 already happened

**Comment by jlprat** [comment]
You kept me wondering! I feared something went wrong and we needed another release!

**Comment by jiminhsieh** [comment]
What I could do:
* 1 PR after 10.0.12 release.

or 

* 2 PRs. The first PR will **not** have the fragment identifier then second PR which will include the fragment identifier.
