### ISSUE TITLE
Update paths image

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http-quickstart-scala.g8#14]
@patrox 3 days ago
Is there an option to update the image file (docs/src/main/paradox/images/hello-akka-http.png) so it reflects the Paths from here ?

**Comment by ennru** [comment]
I assume this was about showing the image when browsing [the sources](https://github.com/akka/akka-http-quickstart-scala.g8/blob/10.2.x/docs/src/main/paradox/index.md#example-app-overview) on Github, that works now.
