### ISSUE TITLE
README.md needs to be updated to the reflect the current state of the Getting Started Guide

### ISSUE THREAD

**Issue by Tilakkumar** [akka/akka-http-quickstart-scala.g8#17]
Hi,

There are no files by name WebServer or WebServerHttpApp.

Regards

**Comment by jlprat** [comment]
You are right. The `README.md` file is not outdated, and doesn't reflect the latest changes applied to the template.
I'll reword the title to make it clearer.

Do you want to help out @Tilakkumar ?

**Comment by Tilakkumar** [comment]
Sure, what do you expect from me?

**Comment by jlprat** [comment]
If you want, you can provide a Pull Request that updates the `README.md` file so it explains correctly how to run and a brief overview of the files there.

**Comment by raboof** [comment]
Fixed in #18
