### ISSUE TITLE
Build project from template on Travis

### ISSUE THREAD

**Issue by raboof** [akka/akka-http-quickstart-scala.g8#19]
It would be cool if travis could apply the template and run the tests of the resulting project when checking a PR.

**Comment by raboof** [comment]
It seems giter8 has [options for selecting branches or tags](https://github.com/foundweekends/giter8/issues/289), but I'm not sure if/how those are exposed to `sbt new`

**Comment by shkoder** [comment]
regarding test run of the generated project - it's already set up like this as:
- ``g8Test`` runs ``test`` of the generated project
- ``test`` is bound to ``g8Test``
- Travis runs ``test``

And it's easy to verify by making one of the template tests fail and running ``sbt test``

**Comment by raboof** [comment]
Oh wow I didn't realize! cool!
