### ISSUE TITLE
When select AKKA 2.5.X is importing 2.4 testkits dependencies

### ISSUE THREAD

**Issue by angelcervera** [akka/akka-http-quickstart-scala.g8#27]
In this moment, using akka 2.5.x import testkits for 2.4

As explain in https://doc.akka.io/docs/akka-http/current/scala/http/compatibility-guidelines.html#akka-http-10-0-x-with-akka-2-5-x, it's neccessary to add:
```
      "com.typesafe.akka" %% "akka-testkit" % akkaVersion % Test,
      "com.typesafe.akka" %% "akka-stream-testkit" % akkaVersion % Test,
```

**Comment by raboof** [comment]
You're right, good catch! In fact these also seems to be missing from https://doc.akka.io/docs/akka-http/current/scala/http/compatibility-guidelines.html#akka-http-10-0-x-with-akka-2-5-x though, right?

**Comment by angelcervera** [comment]
Yes, you are right. Also missed from the documentation.

**Comment by angelcervera** [comment]
PR created to update the documentation and closing the issue. https://github.com/akka/akka-http/pull/1483
