### ISSUE TITLE
SBT Warning: Conflicting versions of akka-stream

### ISSUE THREAD

**Issue by tgambet** [akka/akka-http-quickstart-scala.g8#30]
Consider the following:

```
> sbt new https://github.com/akka/akka-http-scala-seed.g8

This is a seed project which creates a basic build for an Akka HTTP
application using Scala.

name [My Akka HTTP Project]:
scala_version [2.12.3]:
akka_http_version [10.0.10]:
akka_version [2.5.4]:
organization [com.example]:

Template applied in .\my-akka-http-project

> cd my-akka-http-project
> sbt update

[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.akka:akka-stream_2.12:2.4.19 -> 2.5.4
[warn] Run 'evicted' to see detailed eviction warnings

```

How to get rid of the warning ? 

Cf [this related stackoverflow post](https://stackoverflow.com/questions/45940458/conflicting-akka-versions-when-using-akka-akka-streams-akka-http).

**Comment by ktoso** [comment]
Please don't cross-post questions right away, it makes answering and tracking what has been answered difficult.

I answered over there and copying my response here.

> This is on purpose and it is picked such with great care -- in order to still allow people who for some reason are on 2.4 and don't want to move (2.5 is fully binary backwards compatible with 2.4 so there's no reason not to upgrade). The compatibility guidelines, including how to run with 2.5 are documented here https://doc.akka.io/docs/akka-http/current/scala/http/compatibility-guidelines.html and the akka bin compat rules are here: doc.akka.io/docs/akka/current/scala/common/binary-compatibility-rules.html

Please read the two documents above, and ask if anything is still unclear.

**Comment by ktoso** [comment]
Depending explicitly on 2.5 will happen soon, please track this ticket: https://github.com/akka/akka-http/issues/1151

**Comment by tgambet** [comment]
I didn't post on stackoverflow. I pasted the link for reference as there was a possible solution on the thread.

Thank you for your answer, all clear.

**Comment by ktoso** [comment]
Cool thanks :)
