### ISSUE TITLE
Add sbt-revolver plugin + docs how to use it

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http-quickstart-scala.g8#4]

**Comment by jlprat** [comment]
I was thinking about this feature and I'm not sure if it makes sense as this project is the seed, and as it, it should try stay minimal and not force many dependencies.
Maybe we can have another template (like the Hello World ones) showcasing several directives, low-level API, client API and how to use `sbt-revolver` to speed up development.
WDYT?

**Comment by ktoso** [comment]
Hm, having more templates means more maintanance overhead - so I'm not sure we should add a lot of them. Just one should be fine.

Perhaps revolver should be rather documented in our docs for example?

**Comment by jlprat** [comment]
Fair point, more templates means more maintenance. Let's add it here as well then. AFAIK, g8 templates can have some docs section right? Maybe we can add some deeper explanation about best practices or common problems. WDYT?

**Comment by jlprat** [comment]
One problem with `sbt-revolver` though... It can't run the "normal" server because it's reading from `stdin`. `HttpApp` supports both reading from `stdin` and termination of VM to signal the shutdown. I will configure `sbt-revolver` to run the `HttpApp` version by default.

**Comment by jlprat** [comment]
Does this issue still make sense, now that this project will be a Getting Started guide?

**Comment by raboof** [comment]
Hmm I think it'd still be nice to have it configured and ready to go, though perhaps it doesn't really need to be part of the quickstart guide itself.

**Comment by jrudolph** [comment]
I think it should be. It usually part of the "quick" component and we have shown it previously in many tutorials because it is so handy.

**Comment by jlprat** [comment]
Just mentioning it because I had the impression that the quick guide should be short and fit into 30 mins reading (that's why testing didn't make it on the first draft of the quick guide)

**Comment by jlprat** [comment]
But as @raboof mentioned, it might still be there but not in the quick guide 👍

**Comment by raboof** [comment]
Done in #34/#35
