### ISSUE TITLE
Unresolved dependency when building

### ISSUE THREAD

**Issue by duarnad** [akka/akka-http-quickstart-scala.g8#46]
Hi, 

When I try to run the project I have the following message : 
sbt.ResolveException: unresolved dependency: org.scalariform#sbt-scalariform;1.8.2: not found

Regards,
Arnaud

**Comment by raboof** [comment]
That's strange, it works fine for me (even after clearing my ~/.ivy2):
```
[info] downloading https://repo1.maven.org/maven2/org/scalariform/scalariform_2.10/0.2.5/scalariform_2.10-0.2.5.jar ...
[info]  [SUCCESSFUL ] org.scalariform#scalariform_2.10;0.2.5!scalariform_2.10.jar (2143ms)
```
Does trying again work? Do you have any proxies or coursier configured in your ~/.sbt?

**Comment by raboof** [comment]
(this might be more of a topic for https://discuss.akka.io unless it really turns out to be a problem in the template... hard to tell at this point though)

**Comment by duarnad** [comment]
You were right : I am behind a corporate proxy and I forgot that I was pointing to our mirror, which may have a problem. I switched temporarily my 'repositories' file with the following configuration : 

```
[repositories]
  local
  sbt-releases-repo: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  sbt-plugins-repo: http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central: http://repo1.maven.org/maven2/
```
And it worked. Thanks for the quick answer,
Regards,
Arnaud
